development:
  adapter: postgresql
  database: hashtag_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: hashtag_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: hashtag_production
  pool: 5
  timeout: 5000
